apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  postgres-db: dGVzdF9wcm9qZWN0
  postgres-user: cG9zdGdyZXM=
  postgres-password: cGFzc3dvcmQ=
  postgres-host: cG9zdGdyZXNfZGI=
  postgres-port: NTQzMg==