apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
    owner: homayoon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      owner: homayoon
  template:
    metadata:
      labels:
        app: postgres
        owner: homayoon
    spec:
      containers:
      - name: postgres
        image: postgres:12.12
        env: 
          - name: "POSTGRES_DB"
            valueFrom: 
              secretKeyRef:
                name: django-secret
                key: postgres-db
          - name: "POSTGRES_USER"
            valueFrom: 
              secretKeyRef:
                name: django-secret
                key: postgres-user
          - name: "POSTGRES_PASSWORD"
            valueFrom: 
              secretKeyRef:
                name: django-secret
                key: postgres-password
        ports:
        - containerPort: 5432
        resources: 
          limits: 
            cpu: "200m"
            memory: "200M"
          requests: 
            cpu: "200m"
            memory: "200M"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
    owner: homayoon
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432